dpdispatcher/ssh_context.py

If the number of files is too much, it will raise an error
"Argument list too long". A solution is to split it to several
commands.
> RuntimeError: Get error code 1 in calling tar czf ... through ssh with job: 57c454d1-1ca2-4b6b-a5c4-8c468898586e . message: /bin/bash: Argument list too long
Also gzip with force overwrite
This will fix the bug "gzip: 570aef2d-1f5f-4de3-b767-d5a2c4a8e41a.tar.gz already exists; not overwritten" if dpgen stop and restart.
impletment deepmodeling/dpgen#380 and deepmodeling/dpgen#384

fix "Argument list too long" for tar command

---

dpdispatcher/ssh_context.py

open_sftp and close_sftp are expensive actions, especially when the
remote server is far away from the local server. This commit stores sftp
in the object and will reduce the frequency of open_sftp.
implement deepmodeling/dpgen#387

store sftp and reduce frequency of open_sftp

---

dpdispatcher/ssh_context.py

The original implementation method removes files one by one using sftp.
If the latency of the remote server is high, it is very slow.
Thus, it's better to use system's `rm` to remove a directory, which may
save a lot of time.
Also, in some supercomputers, it's very slow to remove large numbers of files
(e.g. directory containing trajectory) due to bad I/O performance.
So an asynchronously option is provided.
Implement deepmodeling/dpgen#385. Close deepmodeling/dpgen#385.

refactor removing directory and provide asynchronous option

---

dpdispatcher/shell.py
dpdispatcher/submission.py

And now it will have the warning like 
> sys:1: ResourceWarning: unclosed file <_io.BufferedReader name=7>
And another warning 
> /some/path/to/dpdispatcher/submission.py:568: ResourceWarning: unclosed file <_io.BufferedReader name=6>
is due to taht when we 'submit' a job  in local shell, we will create a subprocess and initialize a shell to run theses commands.  So the process still exist after we 'submit'  the job to a shell which is just what we expect.

fix ResourceWarning in issue #47 (#issue41 comment 8)

---

dpdispatcher/shell.py
dpdispatcher/ssh_context.py

This PR fix two problem.
**The first** is #78, here using `pathlib` to deal with path format different between Win and POSIX. Changed file `ssh_context.py`.
**The second** is a call() issue when directly using shell. Hope it will return correct pid. Changed file `ssh_context.py` and `shell.py`.
**NOTE:** I'm not sure whether changes of `call()` in `ssh_context.py` will influence other functions.
So far, tests on slurm and shell are without any new problem.

Fix `path` format between Windows and POSIX, also ssh call() return.

---

dpdispatcher/__init__.py

see https://stackoverflow.com/a/2267567/9567349
fix printing to screen twice (fix https://github.com/deepmodeling/dpdispatcher/issues/79#issuecomment-872556042)

prevent logging from being send to the upper logger

---

dpdispatcher/__init__.py

if meet permission error when dumping dpdispatcher.log, will try to redirect the log to ~/dpdispatcher.log

if meet permission error when dumping dpdispatcher.log, will try to redirect the log to ~/dpdispatcher.log

---

dpdispatcher/slurm.py

Currently only logging finished when squeue is successful

slurm: logging finished when squeue error

---

dpdispatcher/lsf.py

In former versions, `kwargs` were not loaded in correct way that may cause `resources.kwargs` to be `{"kwargs": "value"}`. So, in LSF part, for using the custom flags to control how to use GPUs, `resources.kwargs['kwargs']` was used.
However, now the bug has been fixed and the LSF part should also be corrected in prevent of error raised.

Fix kwargs error for LSF

---

dpdispatcher/slurm.py
tests/test_slurm_script_generation.py

--parsable
Outputs only the job id number and the cluster name if present.
The values are separated by a semicolon. Errors will still be displayed.
Ref: https://slurm.schedmd.com/sbatch.html

slurm: use --parsable argument

---

dpdispatcher/ssh_context.py

In `ssh_context.py`
```python
def _walk_directory(self, files, work_path, file_list, directory_list):
"""Convert input path to list of files and directories."""
for jj in files :
file_name = os.path.join(work_path, jj)
```
so `files` should be path of the files relative to `work_path`, not `local_root`.

Fix wildcard relative path in filename

---

dpdispatcher/submission.py

See #118.
This bug is caused by #112. `submission.local_root` is `None` when recovered.

fix `Recovered failed`

---

dpdispatcher/submission.py
tests/jsons/submission.json
tests/test_class_resources.py
tests/test_class_submission.py
tests/test_class_task.py

update unittest; fix fail_count bug in issue #113

update unittest; fix fail_count bug in issue #113

---

dpdispatcher/ssh_context.py

See https://stackoverflow.com/a/5076204/9567349.
This is useful to https://github.com/deepmodeling/deepmd-kit/pull/1055.

ssh: archieve files the symlink points to instead of symlink iteself

---

dpdispatcher/__init__.py
dpdispatcher/distributed_shell.py
dpdispatcher/dp_cloud_server.py
dpdispatcher/dp_cloud_server_context.py
dpdispatcher/machine.py
dpdispatcher/submission.py
tests/jsons/resources.json
tests/sample_class.py

The envs argument now accepts list and variable. 
before I have to write：
{
"envs":{
“LD_LIBRARY_PATH”：”/public/home/ac46q4orcq/dp-2.0/deepmd_root/lib:/public/home/ac46q4orcq/dp-2.0/tensorflow_root/lib:$LD_LIBRARY_PATH“
}
}
now it can write as :
{
"envs":{
“LD_LIBRARY_PATH”：[
”/public/home/ac46q4orcq/dp-2.0/deepmd_root/lib:$LD_LIBRARY_PATH“,
"/public/home/ac46q4orcq/dp-2.0/tensorflow_root/lib:$LD_LIBRARY_PATH"
}
}

add module purge, improve envs and upload oss path with random address.

---

.github/workflows/mirror_gitee.yml
dpdispatcher/lsf.py
dpdispatcher/submission.py
tests/jsons/resources.json
tests/sample_class.py

For some special queue or host, job submission might require waiting time after each single job submitted, to prevent crash when tasks were submitted together. Therefore, parameter `wait_time` is added to `Resources`, to support the special issue. 
The default value of `wait_time` is 0, and it accepts a value of `int`. If set to a value larger than 0, it will sleep for `wait_time` seconds after each job submission. 
Also, a condition is added for `mirror_gitee` action to prevent error message after pushing to the forked repository instead of the main one.

add wait_time to Resources for delayed submission

---

dpdispatcher/slurm.py

fix tag path bug in slurm for job array

fix tag path bug in slurm for job array

---

dpdispatcher/submission.py

When a job previously failed, retries submitting, but is not submitted,
the job id should be cleaned. Otherwise, it will be considered failed
again (although it isn't actually submitted.)

fix a bug in repeat submission

---

dpdispatcher/submission.py

`json.dumps` should be safer to obtain consistent string.

 hash/compare from `json.dumps`

---

dpdispatcher/ssh_context.py
tests/context.py
tests/old/test_ssh_context.py
tests/shell/test_shell_ssh.py

The latter will not catch `KeyboardInterrupt` and `SystemExit`. See https://stackoverflow.com/a/18982726/9567349.

batch replace 'except:' with 'except Exception:'

---

dpdispatcher/ssh_context.py

Writing files may be affected by the network, so we do not override the original file.
This method should have be covered by the unit test.

ssh: create a temporary file when writing a file

---

.github/workflows/test.yml

For unclear reasons, only Python 3.8 sometimes hangs forever.
Though, I cannot reproduce it on the local machine.

comment python 3.8 tests; add 3.10

---

dpdispatcher/ssh_context.py
tests/test_ssh_context.py

For a large number of small files, compression can be very CPU-intensive and time-consuming. See https://github.com/deepmodeling/dpgen/issues/766. 
Add `tar_compress` in dict `remote_profile`. The archive will be compressed in upload and download if it is True. If not, compression will be skipped.

Support optional compress for SSHContext 

---

dpdispatcher/__init__.py
dpdispatcher/submission.py

`wait_time` is add for resubmit, for it would cause the crash just like direct submission.
The generation of empty log file is also fixed just like the former dpgen implementation.

some bug fix and improvement

---

dpdispatcher/ssh_context.py

This PR tends to solve  https://github.com/deepmodeling/dpdispatcher/issues/244 the ssh banner timeout error when using in high concurrency scenario. I enlarge the banner timout parameter from the default 15 to 60.

Enlarge banner timout

---

.github/workflows/test.yml
setup.py

The original package is patched in https://github.com/njzjz/mock-ssh-server/commit/646b6c9031b4e7e6685ce4142014d0ab10a07a86 to close `Popen`.

change source of mock-ssh-server; uncomment 3.8

---

dpdispatcher/ssh_context.py

ssh: move remote_root when it changes

---

ci/pbs.sh
ci/slurm.sh
ci/ssh.sh
ci/ssh_rsync.sh

Codecov python package is deprecated does not work any more. This patch migrates it to another version.

fix codecov

---

dpdispatcher/ssh_context.py

add `look_for_keys` option

---

dpdispatcher/submission.py

For quick test, it might be in need of dry-run instead of just returning after submission really take effect. For easily debug, `dry_run` is add as a choice to make it possible to only put the input files onto work_path but not really submitted. 
While the feature requested and reviewed, it might be a question whether a so-called dry-run should contain the step of uploading instead of just print the file on the screen. Maybe more discussion in need?

add dry_run for run_submission()

---

dpdispatcher/dp_cloud_server_context.py

when groupid is invalid , it will fetch all user`s jobs without groupid limitation.

use jobid to fetch job info

---

dpdispatcher/slurm.py

The `squeue` command occasionally raises the error message `Invalid user for SlurmUser slurm, ignored`. This issue may be related to the network connectivity and is typically resolved within a few seconds. It appears that the error could be misleading, as it could be caused by a temporary network issue rather than a genuine account problem.
As a temporary solution, it would be helpful to modify the code to handle this scenario more gracefully. Instead of raising an error, I just add a condition that triggers a `RetrySignal` in case of the mentioned error. This approach should help distinguish between actual network and account issues. By implementing this change and allowing for three retries, we can likely resolve the problem without causing conflicts with genuine network or account …

Add retry for "Invalid user for SlurmUser"

---

dpdispatcher/base_context.py
dpdispatcher/dp_cloud_server_context.py
dpdispatcher/hdfs_context.py
dpdispatcher/lazy_local_context.py
dpdispatcher/local_context.py
dpdispatcher/lsf.py
dpdispatcher/machine.py
dpdispatcher/pbs.py
dpdispatcher/shell.py
dpdispatcher/slurm.py
dpdispatcher/ssh_context.py
dpdispatcher/submission.py
tests/test_run_submission_ratio_unfinished.py

The current job kill feature is implemented in the `Context`. This is not correct, the command to kill the job is related and only related to `Machine`. This PR reimplements this feature in the `Machine` classes.

refactor job kill

---

dpdispatcher/slurm.py
dpdispatcher/submission.py

Currently, `ratio_unfinished` calculates the ratio of unfinished jobs. When `group_size > 1`, the ratio of unfinished tasks should be more valuable, and we don't need to drop finished tasks in unfinished jobs.

support `ratio_unfinished` in the task level 

---

dpdispatcher/slurm.py

When the account isn't limited and the number of jobs exceeds DEFAULT_MAX_JOB_COUNT, the error will be thrown as
> Slurm temporarily unable to accept job, sleeping and retrying
Here we catch this error and skip the submitting.

slurm: bypass when the number of jobs exceeds the slurm limitation

---

dpdispatcher/submission.py

Currently, if recover, Submission.belonging_tasks[i] and Submission.belonging_jobs[i].job_task_list[j] are different objects, leading to odd behaviors.
Initilize task.task_state from job.job_state.

fix Submission.belonging_tasks if recover

---

dpdispatcher/ssh_context.py
tests/test_ssh_context.py

remove temp hash empty dir when recovered

---

dpdispatcher/submission.py
tests/test_run_submission.py

Feat #347 
1. add `check_interval`
2. add `async_run_submission` method
3. add unittest of the async func
Known bugs:
Async submission may fail on pbs/slurm queue system, but success on lazylocal test.

feat(submission): add async submission and unittest

---

doc/batch.md
dpdispatcher/__init__.py
dpdispatcher/fugaku.py
tests/jsons/machine_fugaku.json
tests/jsons/machine_local_fugaku.json

Added a new batch type for use on Fugaku, a supercomputer using Fujitsu's unique job scheduler.
It has been tested on Dpgen for 20 iterations and no problems have been found.
Also uploaded JSON files for both local and ssh cases.

add new batch_type Fugaku

---

dpdispatcher/ssh_context.py

One currently gets a `RecursionError` when a broken symbolic link is uploaded, as it tries to walk again and again.

ssh: raise clear error when broken symbolic link is found

---

dpdispatcher/ssh_context.py

When user provides key_filename and it does not exist, it's expected to throw an error.

throw errors if key_filename is not found

---

dpdispatcher/ssh_context.py

This PR will enable the usage of the "timeout" keyword and support dpdispatcher for machines which require a long time to connect.

pass timeout to paramiko's Transport

---

dpdispatcher/contexts/hdfs_context.py
dpdispatcher/contexts/local_context.py
dpdispatcher/contexts/ssh_context.py
tests/test_local_context.py

#409 avoids retry in loop when the file is not found in the ssh context. But it is not apply to other contexts, and the tests hang in https://github.com/deepmodeling/dpgen/pull/1406 due to retry.

raise FileNotFoundError in several contexts
