deepmodeling/dpdispatcher

- .travis.yml
- tests/context.py
- tests/test_dispatcher_utils.py
- tests/test_lazy_local_context.py
- tests/test_local_context.py
- tests/test_local_session.py
- tests/test_ssh_context.py
> add support for travis

- .travis.yml
> delete variable in  travis

- .gitignore
- README.md
- dpdispatcher/batch.py
- dpdispatcher/dp_cloud_server.py
- dpdispatcher/dp_cloud_server_context.py
- dpdispatcher/dpcloudserver/api.py
- dpdispatcher/dpcloudserver/config.py
- dpdispatcher/lazy_local_context.py
- dpdispatcher/local_context.py
- dpdispatcher/pbs.py
- dpdispatcher/shell.py
- dpdispatcher/slurm.py
- dpdispatcher/ssh_context.py
- dpdispatcher/submission.py
- setup.py
- tests/devel_test_dp_cloud_server.py
- tests/devel_test_lsf.py
- tests/devel_test_slurm.py
- tests/jsons/job.json
- tests/jsons/machine_dp_cloud_server.json
- tests/jsons/resources.json
- tests/jsons/submission.json
- tests/jsons/task.json
- tests/sample_class.py
- tests/script_gen_json.py
add support for dpcloudserver; fix unittests; modify script generation
> add support for dpcloudserver; fix unittests; modify script generation

- dpdispatcher/pbs.py
fix deepmodeling/dpgen#395
Implement deepmodeling/dpgen#396
> add another check_status option for psate (PBS)

- dpdispatcher/ssh_context.py
Fix deepmodeling/dpgen#379.
implement deepmodeling/dpgen#382
> fix SSH session not active

- dpdispatcher/slurm.py
- dpdispatcher/ssh_context.py
implement deepmodeling/dpgen#276, deepmodeling/dpgen#381
> retry slurm commands when failing

- dpdispatcher/__init__.py
> fix install

- dpdispatcher/slurm.py
- dpdispatcher/ssh_context.py
- dpdispatcher/submission.py
implement #32; also refactor #24
> skip submitting if the job violates QOS policy

- dpdispatcher/slurm.py
> fix function typo

- dpdispatcher/dpcloudserver/temp_test.py
- dpdispatcher/submission.py
fix bug in argument check; clean private info
> fix bug in argument check; clean private info

- dpdispatcher/__init__.py
- dpdispatcher/slurm.py
- tests/test_import_classes.py
support import classes from top level  #44  
#41 comment1 
@njzjz  @y1xiaoc
>  support import classes from top level

- doc/getting-started.md
- dpdispatcher/machine.py
- tests/devel_test_slurm.py
> fix scirpt generation bugs

- doc/index.rst
- doc/resources.rst
- add resources parameters to doc
> add resources parameters to doc

- doc/machine-auto.rst
- doc/resources-auto.rst
- dpdispatcher/machine.py
@felix5572  How can I regenerate the documents?
> add doc_clean_asynchronously

- doc/getting-started.md
- dpdispatcher/machine.py
> update docs usage example

- dpdispatcher/slurm.py
> slurm get job id error

- dpdispatcher/slurm.py
> fix slurm analyze job_id bug

- doc/getting-started.md
- doc/index.rst
- doc/task.rst
> add task parameters into documents

- dpdispatcher/dpcloudserver/api.py
- dpdispatcher/dpcloudserver/zip_file.py
- dpdispatcher/local_context.py
- dpdispatcher/machine.py
- dpdispatcher/shell.py
- dpdispatcher/submission.py
- tests/test_shell_cuda_multi_devices.py
fix bug; will not tag job_tag_finished if one of the tasks fail
> fix bug; will not tag job_tag_finished if one of the tasks fail

- tests/test_local_context.py
> fix unittest

- dpdispatcher/base_context.py
- dpdispatcher/dp_cloud_server_context.py
- dpdispatcher/lazy_local_context.py
- dpdispatcher/local_context.py
- dpdispatcher/machine.py
- dpdispatcher/ssh_context.py
- tests/context.py
- tests/test_class_machine_dispatch.py
- tests/test_shell_trival.py
support `__init__` method as well as load_from_dict method #41  comment10
> support __init__ method as well as load_from_dict method

- dpdispatcher/__init__.py
- dpdispatcher/dpcloudserver/api.py
- dpdispatcher/submission.py
- setup.py
> fix Installation

- dpdispatcher/dp_cloud_server.py
update dpcloudserver error message
> update dpcloudserver error message

- dpdispatcher/ssh_context.py
fix bug: will upload empty dirs for tasks
> fix bug: will upload dirs for tasks

- dpdispatcher/ssh_context.py
> upload main directory non-recursively

- dpdispatcher/slurm.py
- custom_gpu_line for slurm system fix #74
> custom_gpu_line for slurm system

- dpdispatcher/machine.py
> fix script generation

- dpdispatcher/ssh_context.py
> fix bug of ssh_context

- dpdispatcher/submission.py
> skip checking finished jobs

- doc/machine-auto.rst
- dpdispatcher/__init__.py
- dpdispatcher/pbs.py
`Torque` is not open-source.
Documentation of `Torque`: https://support.adaptivecomputing.com/torque-resource-manager-documentation/
This pr is to solve #84.
I think there are better solutions, but I try not to change other code.
> Add `Torque` support.

- dpdispatcher/submission.py
fix bug Resources load_from_dict duplicated kwargs
> fix bug Resources load_from_dict duplicated kwargs

- dpdispatcher/__init__.py
extra "logging.logging" in error handling on line 13
> correct extra "logging" typo

- dpdispatcher/submission.py
- tests/jsons/machine_lazy_local_slurm.json
- tests/test_slurm_script_generation.py
better logic when handle kwargs; fix bug of custom_gpu_line;
> better logic when handle kwargs; fix bug of custom_gpu_line;

- dpdispatcher/local_context.py
support wildcards for local_context upload files
> support wildcard match for local_context upload files

- dpdispatcher/ssh_context.py
> Convert input path to list of files and directories

- dpdispatcher/ssh_context.py
ssh_context support wildcards while uploading
> ssh_context support wildcards while uploading

- dpdispatcher/submission.py
add getitem method for class Resources Task Submission
> add getitem method for class Resources Task Submission

- dpdispatcher/dp_cloud_server.py
update debug information for dpcloudserver
> update debug information for dpcloudserver

- dpdispatcher/dp_cloud_server.py
tolerate failure for one time when query dp_cloud_server
> tolerate failure for one time when query dp_cloud_server

- dpdispatcher/dp_cloud_server.py
- dpdispatcher/submission.py
better debug information when job is terminated
> better debug information when job is terminated

- dpdispatcher/submission.py
- tests/jsons/submission.json
- tests/test_class_submission.py
update class submission; will record local_root in machine to avoid conflicts
> update class submission; will record local_root in machine to avoid conflicts

- requirements.txt
- setup.py
psutil is not being used anywhere.
> remove psutil as not being used

- requirements.txt
- scripts/script_gen_dargs_json.py
- setup.py
add a script to generate argument json file
> add a script to generate json file

- doc/machine-auto.rst
- doc/task-auto.rst
- dpdispatcher/ssh_context.py
- dpdispatcher/utils.py
> support TOTP

- dpdispatcher/__init__.py
- dpdispatcher/machine.py
> Correct doc of PR#86.

- dpdispatcher/dp_cloud_server.py
- dpdispatcher/dp_cloud_server_context.py
- dpdispatcher/dpcloudserver/api.py
http://caokai.deepmd.net/apidoc/#api-Data-PostDataVersionInsert_job
for using v2 API, user have to specify "api_version" in "input_data". The advantage of using v2 is multiple jobs can be grouped as one for better visualization. Also support scass_type or instance_group_id where user can use pre-defined machine type or group of machine type.
> Machine support Lebesgue V2 API

- dpdispatcher/dp_cloud_server_context.py
- dpdispatcher/hdfs_context.py
- dpdispatcher/lazy_local_context.py
- dpdispatcher/local_context.py
- dpdispatcher/machine.py
- dpdispatcher/ssh_context.py
- dpdispatcher/submission.py
- tests/jsons/submission.json
- tests/script_gen_json.py
- tests/test_class_machine.py
- tests/test_class_machine_dispatch.py
- tests/test_class_submission.py
modify submission.json format; will contain machine information in submission.json
> modify submission.json format; will contain machine information in submission.json

- dpdispatcher/ssh_context.py
cherry-pick from deepmodeling/dpgen#593.
> change compress level to 6 from default 9 to accelerate

- dpdispatcher/ssh_context.py
prevents paramiko hang
See also https://github.com/paramiko/paramiko/issues/448.
> use sftp to transfer sha256sum results

- dpdispatcher/ssh_context.py
Per https://superuser.com/a/565974, combining tar and gzip would bring a better I/O performance.
> refactor taring a large number of files

- conda/meta.yaml
> add `tqdm` to conda recipe

- dpdispatcher/ssh_context.py
- dpdispatcher/utils.py
rsync is much faster and more stable than paramiko sftp!
TODO: supports password, port, key_filename, passphrase, etc.
> automatically switch to rsync backend

- doc/getting-started.md
- dpdispatcher/submission.py
> Doc typo fix

- dpdispatcher/ssh_context.py
> add doc to deprecate password

- dpdispatcher/dp_cloud_server_context.py
- dpdispatcher/machine.py
- dpdispatcher/submission.py
- setup.py
- tests/test_argcheck.py
- tests/test_class_machine_dispatch.py
We may need to check again - are all arguments correct?
> enable strict check for arguments

- dpdispatcher/ssh_context.py
> Fix symlink subdirs not uploaded to remote

- doc/examples/g16.md
- examples/task/g16.json
>   add a gaussian 16 example

- doc/examples/shell.md
- dpdispatcher/submission.py
- examples/resources/mandu.json
- tests/test_group_size.py
by setting
```json
"group_size": 0
```
> support infinite group_size

- dpdispatcher/submission.py
Space is missing between two sentences.
> fix grammar in error messages

- dpdispatcher/pbs.py
> fix Torque header format

- dpdispatcher/lsf.py
For a simple solution, I just add retry for LSF submission and status checking like the Slurm way.
Just as a part of #208.
> add retry for LSF

- dpdispatcher/distributed_shell.py
"resource" is not defined in distributed_shell.py
> Change from "resource" to "resources"

- dpdispatcher/lsf.py
- dpdispatcher/slurm.py
- dpdispatcher/utils.py
- tests/context.py
- tests/test_retry.py
> add retry decorator

- dpdispatcher/lsf.py
- dpdispatcher/slurm.py
> refactor the rest codes for retry decorator

- dpdispatcher/ssh_context.py
> catch socker.timeout for ssh exec_command

- dpdispatcher/ssh_context.py
> fix authing using secrets and totp

- .github/workflows/machines.yml
- ci/LICENSE
- ci/README.md
- ci/ssh.sh
- ci/ssh/docker-compose.yml
- ci/ssh/start-ssh.sh
- setup.py
- tests/test_ssh_context.py
It is more stable to test ssh.
> migrate ssh ci test to docker

- .github/workflows/machines.yml
- ci/ssh_rsync.sh
- dpdispatcher/ssh_context.py
- dpdispatcher/utils.py
> support port and key_filename for rsync

- tests/test_ssh_context.py
> add tests for empty transfer

- doc/batch.md
sever -> server in #266 
Thanks for the helpful document!
> Fix typo in pr#266

- dpdispatcher/utils.py
> add Optional to type hints when default is None

- dpdispatcher/dp_cloud_server_context.py
- dpdispatcher/machine.py
> fix bohrium remote root

- .pre-commit-config.yaml
- dpdispatcher/ssh_context.py
- dpdispatcher/utils.py
> format numpydoc

- dpdispatcher/machine.py
- dpdispatcher/ssh_context.py
- dpdispatcher/submission.py
> fix type None - None is not a type

- .github/workflows/pyright.yml
> pin pyright version to 1.1.312

- dpdispatcher/distributed_shell.py
- dpdispatcher/dp_cloud_server.py
- dpdispatcher/fugaku.py
- dpdispatcher/lsf.py
- dpdispatcher/openapi.py
- dpdispatcher/pbs.py
- dpdispatcher/shell.py
- dpdispatcher/slurm.py
- dpdispatcher/submission.py
- dpdispatcher/utils.py
- tests/test_lsf_script_generation.py
- tests/test_slurm_script_generation.py
> support customized template header

- dpdispatcher/ssh_context.py
Fix regression caused by #370.
> ssh: recover default remote_root to None

- dpdispatcher/distributed_shell.py
- dpdispatcher/dp_cloud_server.py
- dpdispatcher/fugaku.py
- dpdispatcher/lsf.py
- dpdispatcher/machine.py
- dpdispatcher/openapi.py
- dpdispatcher/pbs.py
- dpdispatcher/shell.py
- dpdispatcher/slurm.py
> Use separate script to prevent submit script too large

- dpdispatcher/machine.py
- dpdispatcher/slurm.py
- dpdispatcher/submission.py
- tests/test_run_submission.py
> forward the error message of the failed task to the screen

- dpdispatcher/submission.py
- dpdispatcher/utils/record.py
- tests/context.py
- tests/test_run_submission.py
> save record of failed submission

- .github/workflows/test.yml
- dpdispatcher/__main__.py
- dpdispatcher/dpdisp.py
- dpdispatcher/entrypoints/submission.py
- dpdispatcher/submission.py
- tests/context.py
- tests/test_cli.py
- tests/test_run_submission.py
> add cli to handle terminated submission

- dpdispatcher/dpcloudserver/client.py
- tests/context.py
> add backward compatibility with dflow

- dpdispatcher/contexts/ssh_context.py
> ssh: catch EOFError

- doc/batch.md
Enhancement 
https://github.com/deepmodeling/dpdispatcher/issues/324
> Update batch.md with Introduction to Sun Grid System(SGE)

- dpdispatcher/dpdisp.py
- dpdispatcher/entrypoints/submission.py
> add --reset-fail-count flag to dpdisp submission

- dpdispatcher/contexts/local_context.py
- tests/test_run_submission.py
> fix copying directory

- tests/test_run_submission.py
> skip test_async_run_submission for LocalContext

- dpdispatcher/contexts/local_context.py
> local_context: make error message more clear

- doc/context.md
Fix https://github.com/deepmodeling/deepmd-kit/issues/3587.
> docs: document the current environment being overridden 
